// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenVanCuong560.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NguyenVanCuong560.Models.NVC0560", b =>
                {
                    b.Property<string>("NVCID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NVCGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NVCName")
                        .HasColumnType("TEXT");

                    b.HasKey("NVCID");

                    b.ToTable("NVC0560");
                });

            modelBuilder.Entity("NguyenVanCuong560.Models.UniversityNVC560", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityNVC560");
                });
#pragma warning restore 612, 618
        }
    }
}
